# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ec7e6f04f9692692b7ed834052557c1b0a6d67beab9c81c9cc31b17dfc031b3dc487e0226158d282e67849f1975d3a2264765371753ad2653724d7a036597d5

test:
  secret_key_base: 97576e61c0a8be066a70f266c8b5d2625cee7f6303c53ae368f06b32a1be0959aab63cd06797c366e3ac00f81aa4aaf73db3923d8797a915ae2bd9b006347dc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
